feat: port battery indicator to bash

diff --git a/bin/battery_indicator_poly b/bin/battery_indicator_poly
--- a/bin/battery_indicator_poly
+++ b/bin/battery_indicator_poly
@@ -1,85 +1,55 @@
-#!/usr/bin/perl
+#!/usr/bin/bash
 #
-# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
-# Copyright 2014 Vivien Didelot <vivien@didelot.org>
-# Moar colorz by Yago Iglesias
+# Author Yago Iglesias
 #
-# Licensed under the terms of the GNU GPL v3, or any later version.
-#
-# This script is meant to use with i3blocks. It parses the output of the "acpi"
-# command (often provided by a package of the same name) to read the status of
-# the battery, and eventually its remaining time (to full charge or discharge).
-#
-# The color will gradually change for a percentage below 85%, and the urgency
-# (exit code 33) is set if there is less that 5% remaining.
 
-use strict;
-use warnings;
-use utf8;
+acpi_value="$(acpi -b)"
 
-my $acpi;
-my $status;
-my $percent;
-my $text;
-my $color;
-my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
+if [ "$acpi_value" == "Battery 0: Not charging, 99%\n" ]; then
+    echo "%{F#c6d0f5}󰁹 99%%{F-}"
+    exit 0
+fi
 
-# read the first line of the "acpi" command output
-open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
-$acpi = <ACPI>;
-close(ACPI);
 
-# fail on unexpected output
-if ($acpi !~ /: (\w+), (\d+)%/) {
-	die "$acpi\n";
-}
+status=$(echo "$acpi_value" | grep -oE 'Discharging|Charging')
+percent=$(echo "$acpi_value" | grep -oE '[0-9]+%')
+percent=${percent::-1}
 
-$status = $1;
-$percent = $2;
-
-open STDERR, '>', '/dev/null' or die "Cannot open /dev/null$!";
 
 # ------ Yago additions ------
-sub print_text(){
-    if($status eq 'Discharging') {
-
-        if ($percent <= 10) {
-            $text = "%{F#e78284}󰁺";
-        } elsif ($percent <= 20) {
-            $text = "%{F#ef9f76}󰁻";
-        } elsif ($percent <= 30) {
-            $text = "%{F#e5c890}󰁼";
-        } elsif ($percent <= 40) {
-            $text = "%{F#c6d0f5}󰁽";
-        } elsif ($percent <= 50) {
-            $text = "%{F#c6d0f5}󰁾";
-        } elsif ($percent <= 60) {
-            $text = "%{F#c6d0f5}󰁿";
-        } elsif ($percent <= 70) {
-            $text = "%{F#c6d0f5}󰂀";
-        } elsif ($percent <= 80) {
-            $text = "%{F#c6d0f5}󰂁";
-        } elsif ($percent <= 90) {
-            $text = "%{F#c6d0f5}󰂂";
-        } else {
-            $text = "%{F#c6d0f5}󰁹";
-        }
-    } else {
-        $text = "%{F#c6d0f5}󰂄";
-    }
-
-    $text .= " $percent";
-
+function print_text(){
+    if [ "$status" == 'Discharging' ]; then
+        if [ "$percent" -le 10 ]; then
+            text="%{F#e78284}󰁺"
+        elif [ "$percent" -le 20 ]; then
+            text="%{F#ef9f76}󰁻"
+        elif [ "$percent" -le 30 ]; then
+            text="%{F#e5c890}󰁼"
+        elif [ "$percent" -le 40 ]; then
+            text="%{F#c6d0f5}󰁽"
+        elif [ "$percent" -le 50 ]; then
+            text="%{F#c6d0f5}󰁾"
+        elif [ "$percent" -le 60 ]; then
+            text="%{F#c6d0f5}󰁿"
+        elif [ "$percent" -le 70 ]; then
+            text="%{F#c6d0f5}󰂀"
+        elif [ "$percent" -le 80 ]; then
+            text="%{F#c6d0f5}󰂁"
+        elif [ "$percent" -le 90 ]; then
+            text="%{F#c6d0f5}󰂂"
+        else
+            text="%{F#c6d0f5}󰂃"
+        fi
+    else
+        text="%{F#c6d0f5}󰂄"
+    fi
 
     # ---------------------------
-    print "$text%%{F-}\n";
+    echo "$text $percent%%{F-}"
 }
 
-print_text() ;
+print_text
 
 # consider urgent flag only on discharge
-if ($status eq 'Discharging' && $percent < 5) {
-    exit(33); # urgent exit code
-}
-
-exit(0);
+[ "$status" == 'Discharging' ] && [ "$percent" -lt 10 ] && exit 33 # urgent exit code
+exit 0
